apiVersion: v1
kind: Namespace
metadata:
  name: sock-shop
  labels:
    app.kubernetes.io/name: sock-shop
    app.kubernetes.io/managed-by: argocd
    # Required for Kyverno network policy enforcement
    environment: production
